# Generated by Django 5.2 on 2025-04-09 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catergory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_img',
            new_name='category_img',
        ),
    ]
