# Generated by Django 5.2 on 2025-04-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catergory', '0003_alter_category_options_alter_category_category_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
